apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app-github
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8s-app-github
  template:
    metadata:
      labels:
        app: my-k8s-app-github
    spec:
      containers:
        - name: my-k8s-app-github
          image: avvarushashank/my-k8s-app-github:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
