apiVersion: v1
kind: Service
metadata:
  name: my-k8s-app-service-github
spec:
  type: NodePort
  selector:
    app: my-k8s-app-github
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30008
